### ISSUE TITLE
[Comms] Görli Testnet Contributors Call #1

### ISSUE THREAD

**Issue by 5chdn** [goerli/testnet#33]
### Görli Testnet Contributors Call #1

Date / Time
- Friday, December 14th, 2018
- [5pm UTC](https://savvytime.com/converter/germany-berlin-to-canada-toronto-ca-san-francisco-china-shanghai/6pm)

Agenda
- Hello, Testnet
  - Singapore?
- Client Updates
  - Parity Clique (WIP)
    - https://github.com/paritytech/parity-ethereum/pull/9981
  - EthereumJS added Görli support
    - https://github.com/ethereumjs/ethereumjs-common/pull/31
  - other clients (if there's anything)
  - Who's next to join the network?
- Tooling Updates
  - CI full testing suite via upstream Gitlab 
    - https://gitlab.parity.io/parity/parity-ethereum/pipelines/27170
  - CI goerli and ad-hoc clique network via Travis 
    - https://travis-ci.org/goerli/parity-goerli/builds/468072881
    - https://github.com/goerli/parity-goerli/pull/26
  - Ethstats Server for PoW and PoA networks (+ Client)
    - https://github.com/goerli/ethstats-server
    - PoA Demo: https://kovan-stats.parity.io/
    - PoW Demo: https://ropsten-stats.parity.io/
    - Bugs and Security
  - One-Way Throttled Bridge Faucet (+ UI)
    - http://goerli.com/bridge
  - Website for Görli
  - What else do we have?
- Görli Classic
  - Testnet name https://twitter.com/eth_classic/status/1067876029975470080
  - Görli Classic? Kotti? Etcetera?
  - Initial genesis, Getc integration
- Operation Issues
  - goerli.com/bridge downtimes
  - stats.goerli.net downtimes

All contributors and volunteers invited. Join Gitter for invite: [gitter.im/goerli/testnet](https://gitter.im/goerli/testnet)

**Comment by thefallentree** [comment]
+1

**Comment by roninkaizen** [comment]
+1

**Comment by thefallentree** [comment]
works for me.

**Comment by thefallentree** [comment]
unfortunately due to some last minute plan change I won't be able to join the call. 
Updates for clique in parity:
1. clique-v3 is released with signer and votes validation logic,  works great!
2. I have some work done on sealing and voting should be done this week. including json rpc.
3. code cleaning and test writing would take longer but more people can join and help after 2 is done. I will try to get an mergable PR out before Christmas! It would help to have an designated reviewer for fast turnaround time. 

Cheers.

**Comment by roninkaizen** [comment]
that was great.
could we have the link to the call(s) here as well?

**Comment by 5chdn** [comment]
**Recording:** https://www.youtube.com/watch?v=FjzQGLf5yjw
