### ISSUE TITLE
Propose Flashbots MEV Validator for Görli

### ISSUE THREAD

**Issue by q9f** [goerli/testnet#77]
There is a team that wants to do MEV research on Görli and this only works by running a validator. 

If you have time, please review the Flashbots validator proposal: [https://hackmd.io/@flashbots/H1xbLiHz_](https://hackmd.io/@flashbots/H1xbLiHz_)

If you don't have time, **please vote in favor of their validator before block** `4_390_000` (within the next four days ~ by end of week):

```
# js console
clique.propose("0x73625f59CAdc5009Cb458B751b3E7b6b48C06f2C", true)

# http rpc
curl -X POST --data '{"jsonrpc":"2.0","method":"clique_propose","params":["0x73625f59CAdc5009Cb458B751b3E7b6b48C06f2C", true], "id":1}' http://127.0.0.1:8545
```

Please confirm the vote here. Thank you.
- [x] `0x000000568b9b5a365eaa767d42e74ed88915c204` POA Network
- [x] `0x22ea9f6b28db76a7162054c05ed812deb2f519cd` ConsenSys/Besu
- [ ] `0x4c2ae482593505f0163cdefc073e81c63cda4107` Nethermind
- [x] `0x8b24eb4e6aae906058242d83e51fb077370c4720` Infura
- [ ] `0x9d525e28fe5830ee92d7aa799c4d21590567b595` Goerli/Ronin
- [ ] `0xa6dd2974b96e959f2c8930024451a30afec24203` Ethereum/Geth
- [x] `0xd9a5179f091d85051d3c982785efd1455cec8699` Prysmatic Labs
- [x] `0xe0a2bd4258d2768837baa26a28fe71dc079f84c7` Goerli/Afri

✅ Status: 5/5 required votes

**Comment by roninkaizen** [comment]
read and understood.
as i figure out how to vote with my validator, i will do.

**Comment by ryanschneider** [comment]
@jparyani what's your ETA on having a 1.10 version of your fork?  Have you been keeping up with the changes in master?  I think it'd be desirable to demonstrate that your fork is Berlin compatible before we vote.  Also are you committed as a team to keeping your validator up and running 24/7?

**Comment by prestonvanloon** [comment]
Prysmatic Labs has voted in favor of this proposal.

**Comment by jparyani** [comment]
> @jparyani what's your ETA on having a 1.10 version of your fork? Have you been keeping up with the changes in master? I think it'd be desirable to demonstrate that your fork is Berlin compatible before we vote. Also are you committed as a team to keeping your validator up and running 24/7?

I've been maintaining the mev-geth fork as a clean rebase on top of the latest stable release (v1.9.25 at the time of this writing). It's only a few commits, and merge conflicts have been very minor when updating, so I'd estimate 5-10 minutes of work to keep up to date. Check out https://github.com/flashbots/mev-geth/commits/master if you're curious to see the commits.

As to v1.10, I'd be happy to get our fork rebased and released on goerli within 24 hours of upstream.

**Comment by egalano** [comment]
Thanks for the proposal @jparyani! That research would be very useful to the community.

In addition to Ryan's comments above, one question I have is if this is a one-time info gathering research experiment or if this will be an ongoing concern. If you only need this information now or occasionally, it might be best to work with an existing validator vs committing to running one continuously. The Ethereum Clique networks have had incidents in the past (both Gorli and Rinkeby) because of validators going offline from lack of maintenance or fading commitment. While some people still call these testnets, developers and product teams rely on them to be online and available and treat them like production integration networks more than testnets. We as the validator group should be evaluating any changes to the validator set with the primary goal of maintaining or improving network health.

Since we're currently at 8 validators and Clique doesn't like tie situations, maybe it is in our best interest to add an additional validator. If so, I'd like to make sure that we can coordinate with you and your team prior to voting to add your validator in case any network consensus issues arise. There is a coordination channel in Gitter which you can join and please exchange contact info with the other validators for emergencies.

**Comment by jparyani** [comment]
> In addition to Ryan's comments above, one question I have is if this is a one-time info gathering research experiment or if this will be an ongoing concern.

This is an ongoing test for us. Having a goerli validator would accomplish 2 things for us:
1. Test that flashbots is compatible with big changes to ethereum consensus (such as 1559). We have our own suite of tests that spins up a local eth network in CI, but I would consider those more to be smoke tests. It's hard to beat testing in the wild.
2. Eventually, we want to allow anyone to live test submitting flashbots bundles to goerli. This would operate roughly how https://relay.flashbots.net/ works on mainnet.

> If you only need this information now or occasionally, it might be best to work with an existing validator vs committing to running one continuously.

Since we're operating a fork of geth, this complicates things. I think we'd be happy if an existing validator did this for us, but it would be a lot of coordination cost keeping them in sync with our work.

> There is a coordination channel in Gitter which you can join and please exchange contact info with the other validators for emergencies.
I've started a conversation there, thanks!

**Comment by q9f** [comment]
> Since we're currently at 8 validators and Clique doesn't like tie situations, maybe it is in our best interest to add an additional validator.

Thanks for bringing this up. We currenlty need 5/8 active nodes. The reason why I support adding another validator is that the threshold stays at 5/9. In a way, we can only win.

On a personal note, if anyone from Besu could respond to my support request on Rocket Chat or Discord, that would be much appreciated (regarding CLIQUE API).

**Comment by q9f** [comment]
Need 3 more votes in today or tomorrow! 🙏🏼

**Comment by egalano** [comment]
Thanks for the responses. Infura will vote in favor of the proposal

**Comment by shemnon** [comment]
besu voted.

**Comment by igorbarinov** [comment]
```
root@goerli-validator:~# curl -X POST --data '{"jsonrpc":"2.0","method":"clique_propose","params":["0x73625f59CAdc5009Cb458B751b3E7b6b48C06f2C", true], "id":1}' http://127.0.0.1:8545

{"jsonrpc":"2.0","result":true,"id":1}
```

from POA validator

**Comment by q9f** [comment]
Thanks, the validator should be active tomorrow!

**Comment by jparyani** [comment]
Thanks all! The node is running and is upgraded to v1.10, although it seems like Berlin has been delayed to v1.10.1.

**Comment by q9f** [comment]
Unfortunately, that did not work.

```
> clique.getSigners()
["0x000000568b9b5a365eaa767d42e74ed88915c204", "0x22ea9f6b28db76a7162054c05ed812deb2f519cd", "0x4c2ae482593505f0163cdefc073e81c63cda4107", "0x8b24eb4e6aae906058242d83e51fb077370c4720", "0x9d525e28fe5830ee92d7aa799c4d21590567b595", "0xa6dd2974b96e959f2c8930024451a30afec24203", "0xd9a5179f091d85051d3c982785efd1455cec8699", "0xe0a2bd4258d2768837baa26a28fe71dc079f84c7"]
```

Did anyone restart the node after voting?

**Comment by ryanschneider** [comment]
It looks like goerli is stalled now, no new blocks in almost an hour, I haven't had time to look into why yet, but might it be related to this vote?

**Comment by q9f** [comment]
No. I see 6 active validators. Clique might be in a deadlock again.

**Comment by q9f** [comment]
Online: 

0x22ea9f6b28db76a7162054c05ed812deb2f519cd 5/25 ConsenSys
0x4c2ae482593505f0163cdefc073e81c63cda4107 4/25 Nethermind
0x8b24eb4e6aae906058242d83e51fb077370c4720 4/25 Infura/EG
0x9d525e28fe5830ee92d7aa799c4d21590567b595 4/25 Görli/Ronin
0xa6dd2974b96e959f2c8930024451a30afec24203 4/25 EF/Geth
0xe0a2bd4258d2768837baa26a28fe71dc079f84c7 4/25 Görli/Afri

Offline
* POA @igorbarinov 
* Prysm @prestonvanloon

**Comment by konradkonrad** [comment]
Not sure if this is the right issue to track this, but an observation: https://goerli.etherscan.io/block/4391762 seems to have pushed the gas limit `> 8_000_000`, and just a few blocks later the network is stuck.

**Comment by q9f** [comment]
Moving to #78

**Comment by jparyani** [comment]
Alright, I've enabled my validator. It's currently running a clean sync of geth v1.10, but let me know if I should downgrade to v1.9

**Comment by q9f** [comment]
Ok, it was a bit bumpy, but closing. Well done and thanks for joining us.

```
> clique.getSigners()
["0x000000568b9b5a365eaa767d42e74ed88915c204", "0x22ea9f6b28db76a7162054c05ed812deb2f519cd", "0x4c2ae482593505f0163cdefc073e81c63cda4107", "0x73625f59cadc5009cb458b751b3e7b6b48c06f2c", "0x8b24eb4e6aae906058242d83e51fb077370c4720", "0x9d525e28fe5830ee92d7aa799c4d21590567b595", "0xa6dd2974b96e959f2c8930024451a30afec24203", "0xd9a5179f091d85051d3c982785efd1455cec8699", "0xe0a2bd4258d2768837baa26a28fe71dc079f84c7"]
```

Let me know if you need anything @jparyani

**Comment by q9f** [comment]
@jparyani can you add your node to the dashboard? https://stats.goerli.net/

DM `@q9#0001` on Discord for secret.

**Comment by jparyani** [comment]
I tried to add him, but I'm unable to. I'm assuming it's a permission issue since we don't share any servers together. Is there a discord server I should join first?

**Comment by roninkaizen** [comment]
from my archive:
git clone https://github.com/goerli/ethstats-client.git stats
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install nodejs
then 
within the clone repo
npm install
npm install -g pm2
now configure your `app.json` matching to your personal details

some basic config being shared now
`      "NODE_ENV"        : "production",
      "RPC_HOST"        : "localhost",
      "RPC_PORT"        : "85xx", where xx means your settings to be applied here
      "LISTENING_PORT"  : "303xx",  where xx means your settings to be applied here
      "INSTANCE_NAME"   : "OpenEthereum Goerli suprn0de",
      "CONTACT_DETAILS" : "roninkaizen@t-online.de",
      "WS_SERVER"       : "ws://stats.goerli.net:3000/api",
`

**Comment by q9f** [comment]
You can also ask in https://gitter.com/goerli/testnet
