### ISSUE TITLE
[Comms] Görli Testnet Contributors Call #1

### ISSUE THREAD

**Issue by roninkaizen** [goerli/testnet#81]

**Comment by prestonvanloon** [comment]
Hey @roninkaizen, I have not heard from many of the goerli validators. Perhaps we should delay this call until more have a chance to respond.

**Comment by prestonvanloon** [comment]
Poll: https://doodle.com/poll/b969d9paxnuy6wgs

Let's move forward with an informal meeting at 14:00 UTC tomorrow. That seemed to have participation from everyone. I'll drop an meeting invite in the gitter chat 15 minutes prior to the start.

**Comment by prestonvanloon** [comment]
Some meeting notes:

- Validators should raise their gas limit to 15M, Flashbots and Besu will increase their gas limits
- Goerli needs validator monitoring. I.e. which validators are online and performing? Is goerli at risk of stalling due to few validators online?
- Meetings should be on a quarterly basis
- Swarm team suggests that their usage of the goerli network will reduce significantly with the launch in mainnet
- Goerli faucets are under high abuse. Prysmatic Labs turned off their faucet indefinitely and will amend the faucet bot to send eth2 deposits on users' behalf. Swarm has adjusted their bonding curve for gBZZ, which may have reduced the demand for gETH from faucets.

**Comment by roninkaizen** [comment]
gathered also consensus about the continouance of Goerli,
incl. preparations
if the actual stats-server is turned off
providing a new stats, reachable at another adress (if needed)
agreed and notified all other validators adjusting their validaor gas limit to 15M
collected confirmations about that as well
gathering feedback about the automated faucet-draining by the swarm fans from slockit and muditgupta
agreed on permant monitoring of all validators, mined blocks,  -->`needs validator monitoring`
